include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    lines_longer_than_80_chars: true
    one_member_abstracts: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    overridden_fields: true
    unnecessary_overrides: true
    annotate_overrides: true
    type_annotate_public_apis: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: false
    prefer_constructors_over_static_methods: true
    avoid_returning_null_for_future: true
